clients:
  - id: testing
    secrets:
    - testing
    name: testing
  - id: wallets
    secrets:
    - wallets
    name: wallets
  - id: orchestration
    secrets:
    - orchestration
    name: orchestration
  - id: control
    secrets:
      - mysupersecret
    redirectUris:
      - http://api.crossfit.lol:3000/auth/login
      - http://api.crossfit.lol/auth/login
      - https://oauth.pstmn.io/v1/callback
    name: control
    postLogoutRedirectUris:
      - http://api.crossfit.lol:3000/auth/destroy
      - http://api.crossfit.lol/auth/destroy
